name: paxterya
version: "0.9.0-snapshot"
author: Paxterya
main: com.paxterya.paxteryaplugin.PaxteryaPlugin
api-version: "1.17"
website: https://paxterya.com
commands:
  paxterya:
    description: debug and maintanance commands
    usage: /<command> reload
  role:
    description: Debug command to get role of a player
    usage: /<command> get <player>
  msg:
    description: Sends a private message to a fellow player
    usage: /<command> <Player> <message>
    aliases: [w, dm]
  r:
    description: Reply to the last private message
    usage: /<command> <message>
  groupdm:
    description: Used to manage group DMs. Create a new group DM; you can only be in one group DM at a time and it will get deleted on server restarts!; Can also be used to leave the current group DM; Show who is in the group DM with you
    usage: /<command> <player1> <player2> ... <playerXX> OR /<command> leave OR /<command> list
    aliases: gdm
  gmsg:
    description: Send a private message to everone in your current group chat
    usage: /<command> message
    aliases: [greply, gr, gm]
  afk:
    description: Manually toggle afk state
    usage: /<command> to go afk and /<command> again to go un-afk
  getafkplayers:
    description: Lists all afk players
    usage: /<command>