roles:
  -
    id: '3'
    name: 'player'
  -
    id: '4'
    name: 'cool'
    prefix: '[§bcool§r]'
  -
    id: '5'
    name: 'mayor'
    prefix: '[§6mayor§r]'
  -
    id: '7'
    name: 'mod'
    prefix: '[§cmod§r]'
    permissions:
      - 'minecraft.command.ban'
      - 'minecraft.command.banlist'
      - 'minecraft.command.gamemode'
      - 'minecraft.command.kick'
      - 'minecraft.command.list'
      - 'minecraft.command.teleport'
      - 'bukkit.command.tps'
      - 'coreprotect.*'
  -
    id: '9'
    name: 'admin'
    prefix: '[§4admin§r]'
    permissions:
      - 'minecraft.command.teleport'
