roles:
  -
    id: '3'
    name: 'player'
  -
    id: '4'
    name: 'cool'
    prefix: '[§bcool§r]'
  -
    id: '5'
    name: 'mayor'
    prefix: '[§6mayor§r]'
  -
    id: '7'
    name: 'mod'
    prefix: '[§cmod§r]'
    permissions:
      - 'minecraft.command.ban'
      - 'minecraft.command.banlist'
      - 'minecraft.command.gamemode'
      - 'minecraft.command.kick'
      - 'minecraft.command.list'
      - 'minecraft.command.teleport'
      - 'bukkit.command.tps'
      - 'coreprotect.*'
  -
    id: '9'
    name: 'admin'
    prefix: '[§4admin§r]'
    permissions:
      - 'minecraft.command.teleport'

#where to use word replacing
replace_words_in:
  global: true
  dm: true

word_replacer_rules:
#Syntax: <word to replace>: '<replacement>'.
#Keywords that are replaced with special player information are:
#'PLAYER_COORDS', 'PLAYER_FULLCOORDS', 'PLAYER_COOLCOORDS', 'PLAYER_BIOME', 'PLAYER_TOOL', 'PLAYER_DIAMONDS',
#'PLAYER_SPAWN', 'PLAYER_PLAYTIME', 'PLAYER_SPEED', 'PLAYER_XP'
  -
    mycoords: 'PLAYER_COOLCOORDS'
    #myfullcoords: 'PLAYER_FULLCOORDS'
    mytool: 'PLAYER_TOOL'
    mydias: 'PLAYER_DIAMONDS'
    myspawn: 'PLAYER_SPAWN'
    myplaytime: 'PLAYER_PLAYTIME'
    mybiome: 'PLAYER_BIOME'
    myspeed: 'PLAYER_SPEED'
    myxp: 'PLAYER_XP'

afkKickTimeMinutes: 6000
